### ISSUE TITLE
Decompressing encrypted 7z file?

### ISSUE THREAD

**Issue by rsm-imap-cc** [fancycode/pylzma#30] opened 2015-07-17 19:42 UTC
Hello, 
I installed pylzma over Debian jessie by doing "pip install pylzma", and it seems that it is faling to decompress an encrypted 7z file that I just created.

_________________________________________________________
import pylzma, os
from py7zlib import Archive7z

with open('./1.7z', 'rb') as f:
    archive = Archive7z(f, password='abc') # the indentation over github is wrong
__________________________________________________________

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    archive = Archive7z(f, password='abc')
  File "/usr/local/lib/python2.7/dist-packages/py7zlib.py", line 742, in __init__
    data += pylzma.decompress(props+tmp, maxlength=folder.unpacksizes[idx])
TypeError: Error while decompressing: 1
_________________________________________________________

Is this a bug, or I'm doing something wrong?

**Comment by fancycode** [comment] 2015-07-28 18:47
I'm assuming this is a duplicate of #26 which has already been fixed in master. Could you please try from there? I will push out a new version later today, so this should then also work with `pip install pylzma`.

**Closed by fancycode** 2015-07-28 18:47 UTC

**Comment by fancycode** [comment] 2015-07-28 19:09
Released as v0.4.8 (v0.4.7 contained the test files and therefore would have been too large)
https://pypi.python.org/pypi/pylzma/0.4.8
