### ISSUE TITLE
UnsupportedCompressionMethodError 

### ISSUE THREAD

**Issue by gzqjy** [fancycode/pylzma#48] opened 2017-07-05 05:01 UTC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/pylzma-v0.4.8_14_gaea5dev_r0-py3.5-linux-i686.egg/py7zlib.py", line 612, in read
    decoder = self._decoders.get(method, None)
py7zlib.UnsupportedCompressionMethodError: b'!'

**Comment by bkuczenski** [comment] 2018-06-30 02:55
This appears to be a duplicate of #43, which is still open and urgent

**Comment by fancycode** [comment] 2018-07-25 21:15
Yes, this is a duplicate of #43, see #51 for a work-in-progress PR that adds support for LZMA2.

**Closed by fancycode** 2018-07-25 21:15 UTC
